zoom: 4
url_path_prefix: /python_maproom

# DB configuration for the production docker environment. Override in
# development environment.
db:
    host: postgres
    port: 5432
    user: ingrid
    dbname: iridb

datasets:
    
    shapes_adm_US-CA:
        - name: National
          color: black
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0
          is_checked: True
        - name: States
          color: grey
          sql: select (adm0_code, adm1_code) as key, adm1_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
            from g2015_2014_1 where adm0_code in (46, 162, 259)
          is_checked: True
    
    shapes_adm_SAMER:
        - name: National
          color: black
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0
          is_checked: True
        - name: States
          color: grey
          sql: select (adm0_code, adm1_code) as key, adm1_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
            from g2015_2014_1
          is_checked: True
    
    shapes_adm_SASIA:
        - name: India-Pakistan
          color: black
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0 where adm0_code in (115, 188)
          is_checked: True
        - name: National
          color: grey
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0
          is_checked: True
        - name: States
          color: grey
          sql: select (adm0_code, adm1_code) as key, adm1_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
            from g2015_2014_1 where adm0_code in (115, 188)
          is_checked: True
    
    shapes_adm_Thailand:
        - name: Thailand-Vietnam
          color: black
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0 where adm0_code in (240, 264)
          is_checked: True
        - name: National
          color: grey
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0
          is_checked: True
        - name: States
          color: grey
          sql: select (adm0_code, adm1_code) as key, adm1_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
            from g2015_2014_1 where adm0_code in (240, 264)
          is_checked: True

maprooms:

    projections:

        # App set up
        - title: Projections
          core_path: projections
